### PR TITLE
CE-440 Remove redundant IAM role for shared concourse worker

### PR DESCRIPTION
**Pull request by danjoneslf**
This terraform created an IAM role trusting the shared concourse worker execution roles. Now that shared concourse has been torn down the IAM trust is no longer valid but the role is no longer required since this action is now performed by CodePipeline using the deployer role.

### CODE REVIEW

**Comment by danjoneslf** [comment]
There are some places referencing the modules in the outputs. I'll make sure all the account TFs plan before marking ready.

**Comment by danjoneslf** [comment]
There are some places referencing the modules in the outputs. I'll make sure all the account TFs plan before marking ready.

**Comment by danjoneslf** [comment]
All changed account TFs plan successfully.

**Review by gds-ahine — APPROVED** [review]
👍

**Pull request merged**
